ADAPT-378 Style global brand bar and masthead with logo
SU-SWS/saa_victoria_subtheme pull request #28
Opened 2020-07-09 22:04 UTC by rebeccahongsf

# NOT READY FOR REVIEW

# Summary
- Style global brand bar and masthead with logo

# Review By (Date)
- will update

# Urgency
- medium

# Steps to Test

1. Pull this branch
2. Clear render cache
3. View local site's masthead/brand bar

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
-[ADAPT-378](https://stanfordits.atlassian.net/browse/ADAPT-378)

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

2020-07-13 17:31 UTC, rebeccahongsf commented
@katrialesser this PR is ready for review. 😄 

I do have a bit of confusion as to what the hover state for the navigation should be. Should the hover state be just the color `#8C1515` or should it be the color AND include the underline?
(see [Figma](https://www.figma.com/file/TXNBECAGcEkZ3vwc6xcZ3g/SAA-Design-System?node-id=876%3A3736))

Currently, I styled the hover state to only change the colors of the inactive tab text to `#8C1515` and the active tab text and underline to `#8C1515`.

Also we might need to swap out the search bar icon for a new svg file in order to change the color to `#2E2D29`. 🤔

2020-07-13 22:10 UTC, rebeccahongsf commented
I've tweaked the search icon button size a bit from `12px` to `18px` since it seems incredible small. Let me know your thoughts and if I should revert back to `12px` 😄

2020-07-13 22:24 UTC, katrialesser requested changes

2020-07-13 22:24 UTC, katrialesser commented on src/scss/components/main-nav/_main-nav.scss
> +      color: #e50808;
Colors should all be in variable names in the scss files. It should auto complete in php storm for you.

If there is ever a color not in there or our saa colors file we can add it to the saa colors file.

2020-07-13 22:24 UTC, katrialesser commented on src/scss/components/main-nav/_main-nav.scss
> +            background-color: #e50808;
The :before element is being removed from the active li on hover; I think we need to adjust the javascript that is controlling this so it doesn't remove the :before element.

2020-07-14 22:24 UTC, katrialesser approved these changes

2020-07-14 22:24 UTC, merged