ADAPT-559 Reorganized file structure for cards and resolved line-height issue
SU-SWS/saa_victoria_subtheme pull request #79
Opened 2020-08-10 20:03 UTC by rebeccahongsf

# READY FOR REVIEW

# Summary
- Reorganized faux and icon cards style files
- Added partial card file for h2 and p tag line height

# Review By (Date)
- asap

# Urgency
- low

# Steps to Test

1. Pull down the branch
2. Clear the site cache
3. Compare Icon Card with WYSIWYG <h2> and <p> tags.

Line height should be:
Mobile: 22.4px
Standard: 35.7px

# Associated Issues and/or People
- [ADAPT-559](https://stanfordits.atlassian.net/browse/ADAPT-559)

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

2020-08-10 20:06 UTC, rebeccahongsf commented
I've removed `icon-card--single-in-row` since it contained font-sizing that should be applied to all with the `.su-card` class. 
Font and line-height styles for `.su-card` can be found within `_card.scss` partial.

2020-08-19 00:24 UTC, katrialesser requested changes
rebuild to resolve css conflict, looks great, except we shouldn't have the @import line for the utilities. Those lines aren't needed now that we have done the webpack reorg.

2020-08-19 00:26 UTC, katrialesser requested changes

2020-08-19 00:26 UTC, katrialesser commented on src/scss/components/card/faux-cards/_faux-card--cta-list.scss
> +@import "../../../utilities/index";
remove - not needed now with the webpack reorg method.

2020-08-19 00:26 UTC, katrialesser commented on src/scss/components/card/faux-cards/_faux-card--fonts.scss
> +@import "../../../utilities/index";
shouldn't be needed.

2020-08-19 00:26 UTC, katrialesser commented on src/scss/components/card/faux-cards/_faux-card--horizontal-general.scss
> +@import "../../../utilities/index";
shouldn't be needed.

2020-08-19 00:26 UTC, katrialesser commented on src/scss/components/card/faux-cards/_faux-card--horizontal-min-circle.scss
> +@import "../../../utilities/index";
shouldn't be needed.

2020-08-19 00:26 UTC, katrialesser commented on src/scss/components/card/faux-cards/_faux-card--horizontal-min-square.scss
> +@import "../../../utilities/index";
shouldn't be needed.

2020-08-19 00:26 UTC, katrialesser commented on src/scss/components/card/faux-cards/_faux-card--layout--media-text-area.scss
> +@import "../../../utilities/index";
shouldn't be needed.

2020-08-19 00:26 UTC, katrialesser commented on src/scss/components/card/faux-cards/_faux-card--vertical-general.scss
> +@import "../../../utilities/index";
shouldn't be needed.

2020-08-19 00:26 UTC, katrialesser commented on src/scss/components/card/faux-cards/_media-caption-text-area-layout.scss
> +@import "../../../utilities/index";
shouldn't be needed.

2020-08-19 00:26 UTC, katrialesser commented on src/scss/components/card/icon-cards/_icon-card.scss
> +@import "../../../utilities/index";
shouldn't be needed.

2020-08-19 00:26 UTC, katrialesser commented on src/scss/components/index.scss
> +//@import '../config/index';
Remove comments.

2020-08-19 16:33 UTC, katrialesser approved these changes

2020-08-19 16:33 UTC, merged